---
title: "Data Analysis FAIRness of Dental Research Data"
author: 'Uribe, Sofi-Mahmudi, Raittio, Maldupa and Vilne'
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
    code_folding: hide
  pdf_document:
    toc: yes
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE, out.width="75%")
# Use include=TRUE for the chunks to be displayed
```

# Packages

```{r}
# if not installed, install 
# install.packages("pacman")
# library(pacman)

pacman::p_load(tidyverse, # for data wrangling and visualizations 
               janitor,   # for data cleaning and tables
               here,      # for files handling
               gtsummary, # for tables
               dataMaid   # for the codebook
               )
```

# Datasets

```{r}
open_data_all <- read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQ_yrHOCcgEu2_VHvxgvQnJaXc1McdyoiCyzUqNNDfBc_9TBHtRNtl6LbM3yQEd8IGElVjqA_llGEto/pub?gid=537877323&single=true&output=csv")
```



Select some columns for the analysis

```{r}
open_data_all <- open_data_all %>%
  select(
    doi_publication,
    title,
    journalTitle,
    pubYear,
    pubType,
    isOpenAccess,
    citedByCount,
    is_open_data,
    open_data_category,
    is_open_code,
    true_open_data,
    study_type,
    dataset_type,
    FAIR_level:FsF_R1.3_02D
  )
```

add index number 
```{r}
open_data_all <- open_data_all %>% 
  rowid_to_column("id")
```


```{r}
names(open_data_all)
```

```{r}
summary(open_data_all)
```


# EDA
## all data

### General

```{r}
open_data_all %>% 
  select(-c(id, 
            doi_publication, 
            title, 
            pubType,
            study_type, 
            dataset_type, 
            FAIR_level:FsF_R1.3_01M
            )) %>% 
  gtsummary::tbl_summary(by = true_open_data)
```



## With FAIRness assessment
```{r}
open_data_all %>% 
  filter(is.na(FAIRness)) %>%  # filter all data with FAIRness evaluation TRUE
  group_by(journalTitle, pubYear) %>% 
  summarise(FAIRness_mean = mean(FAIRness, na.rm = T)) %>% 
  pivot_wider(names_from = pubYear, values_from = FAIRness_mean )
```





# Codebook

(run only once at the end of the analysis)
```{r}
# open_data_all %>% 
#  dataMaid::makeCodebook()


```

```{r}
# sessionInfo() 
```


